### ISSUE TITLE
Simple stack form - inputProps should be typed correctly

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [bholmesdev/simple-stack#28]
### Astro Info

```block
Astro                    v4.1.1
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/alpinejs
                         simple-form
```

### Describe the Bug

Currently inputType is not correctly typed. It's type is set to:
```
inputProps: Record<string, InputProp>;
```

Which means that if we do this:
```
const form = createForm({
  example: z.string()
});
---
<input {...form.inputProps.wrongNameHere} />   <-- we can put incorrect field name here
```

### What's the expected result?

Type should be inferred from the object passed to createForm.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-88vj7a?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Should be fixed in v0.1.8! And I saw you were willing to submit a PR in that bug report. Definitely keep the issues coming and I'm happy to work with you on your first PR :)
