### ISSUE TITLE
Could not find a declaration file for module 'simple-stack-form'

### ISSUE THREAD

**Issue by teinett** [bholmesdev/simple-stack#4]
I follow your video stream https://www.youtube.com/watch?v=zDybmbaSZxE/

I import form package to `astro.config.mjs` and receive typescrpt warning:

```
Could not find a declaration file for module 'simple-stack-form'. '/Users/teine/Development/landing-template/node_modules/simple-stack-form/src/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/simple-stack-form` if it exists or add a new declaration (.d.ts) file containing `declare module 'simple-stack-form';`
```

My file `src/env.d.ts`:
```
/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference types="simple-stack-form/types" />
```

Screenshot:

<img width="875" alt="Screenshot 2023-12-08 at 14 40 10" src="https://github.com/bholmesdev/simple-stack/assets/1038168/ee8c0fdd-f6ff-4195-9867-dce0e1b3aff1">

**Comment by bholmesdev** [comment]
Fix published in v0.0.6!
