### ISSUE TITLE
Sanitizing user inputs

### ISSUE THREAD

**Issue by teinett** [bholmesdev/simple-stack#6]
My form:
```
---
import { z } from "astro/zod";

const form = await Astro.locals.form.getData({
    // sanitize name
    name: z.string().trim().min(2).max(100),

    // sanitize contacts
    contacts: z.string().trim().min(2).max(200),
});

if (form?.success) {
    console.log("Form data \n", form);
}
---
```

Should I use anything to sanitize form additionally? 

I want to protect the form from XSS attacks: `userInput = "<script>alert('XSS attack');</script>"`

**Comment by bholmesdev** [comment]
Yes, you'll need to handle sanitization of user inputs right now! Could see a first-class solution in the future. For now, consider a library like [sanitize-html](https://www.npmjs.com/package/sanitize-html)

**Comment by teinett** [comment]
An example of how to use this library [sanitize-html](https://www.npmjs.com/package/sanitize-html) together with your package and zod validation would be very helpful. 

Can you add this example to the readme file please? 
Or show it in future streams?

**Comment by bholmesdev** [comment]
I certainly can! Apologies for closing prematurely as well. I was treating GitHub issues as "bug reports only" similar to the Astro core repository. But since I haven't laid the groundwork for templates or a place for feature requests, happy to discuss here.

**Comment by bholmesdev** [comment]
This is now documented in the README!
