### ISSUE TITLE
Lighthouse - robots.txt is not valid

### ISSUE THREAD

**Issue by ya-lops** [bholmesdev/simple-stack#60]
### Astro Info

```block
Astro                    v4.4.13
Node                     v20.11.0
System                   Windows (x64)
Package Manager          yarn
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/mdx
                         simple-stream
```

### Describe the Bug

got `robots.txt`

content:
`User-agent: *`
`Allow: /`

When checking Lighthouse in the SEO section, a message appears about incorrect robots.txt content

report:
https://pagespeed.web.dev/analysis/https-devlinx-vercel-app/2n9b8n956h?form_factor=desktop

![image](https://github.com/bholmesdev/simple-stack/assets/10981641/e48a0a9f-d9ea-4194-985e-96ac66715c2d)

### What's the expected result?

No errors. All fine)

### Link to Minimal Reproducible Example

https://devlinx.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting @ya-lops! Unfortunately, a reproduction without a link to the source isn't very helpful. Do you mind sharing this? And if not, can you share a stackblitz reproduction using astro.new?

**Comment by ya-lops** [comment]
> Thanks for reporting @ya-lops! Unfortunately, a reproduction without a link to the source isn't very helpful. Do you mind sharing this? And if not, can you share a stackblitz reproduction using astro.new?

https://github.com/ya-lops/devlinx

**Comment by ya-lops** [comment]
moved `robots.txt` to public! all fine!
![image](https://github.com/bholmesdev/simple-stack/assets/10981641/0184050f-ac30-4d07-a95a-438de88f6704)

**Comment by ya-lops** [comment]
so i closing. its my own issue. my robot lived in wrong place
