### ISSUE TITLE
Error on Middleware not returning a `Response` or calling `next` function

### ISSUE THREAD

**Issue by dsnjunior** [bholmesdev/simple-stack#9]
Hi! I'm experiencing this issue on my project:

```
[ERROR] [MiddlewareNoDataOrNextCalled] The middleware needs to either return a `Response` object or call the `next` function.
  Error reference:
    https://docs.astro.build/en/reference/errors/middleware-no-data-or-next-called/
  Stack trace:
    at [...]/.pnpm/astro@4.0.3_typescript@5.2.2/node_modules/astro/dist/core/middleware/callMiddleware.js:27:13
    [...] See full stack trace in the browser, or rerun with --verbose.
```

I've changed this [line](https://github.com/bholmesdev/simple-stack/blob/main/packages/form/src/middleware.ts#L55) to `return next();` locally and it worked. But I don't know if I am doing something wrong.

**Comment by bholmesdev** [comment]
Huh, I'm surprised we need to _return_ the next function there. Can you run `astro info` and paste the result here?

**Comment by dsnjunior** [comment]
```
Astro                    v4.0.3
Node                     v18.17.0
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/react
                         @astrojs/tailwind
                         simple-form
```

**Comment by dsnjunior** [comment]
I tried upgrading the node version, and I did upgrade the astro version and integrations with `pnpm dlx @astrojs/upgrade` and now it is `v4.0.4` but the error is still there. This is weird because on my middleware, I really don't need to return `next()`, but when I add the simple stack form integration, it breaks.

**Comment by bholmesdev** [comment]
Huh, pretty strange. Did you install the integration with `astro add simple-stack-form` or apply to a `middleware.ts` file manually?

**Comment by dsnjunior** [comment]
I installed it using the `astro add simple-stack-form` command. Should I try doing it manually?

**Comment by bholmesdev** [comment]
Nope, that's the preferred flow. If there's a github repo you can link to repro, that could help! Also curious if you can repro in an empty project (say running `npm create astro@latest --template minimal`)

**Comment by dsnjunior** [comment]
I did it, and it looks like there is something related to an async call in my middleware. It was probably my fault.

In the empty project, if I have this middleware, I get the same `MiddlewareNoDataOrNextCalled` error:
```ts
import { defineMiddleware } from "astro/middleware";

export const onRequest = defineMiddleware(async (context, next) => {
  await new Promise((resolve) => setTimeout(resolve, 400));
  next();
});
```

But if I remove it, it works as expected. The same happened when I removed an async call from my original project's middleware.

**Comment by bholmesdev** [comment]
@dsnjunior Ah ha, very interesting! I _might_ be wrong but this feels like an issue in Astro core. I'll ping our team to see if it's worth a GitHub issue. Closing for now but hope you're unblocked 🙌

**Comment by bholmesdev** [comment]
Should be fixed in version 0.1.2 👍

**Comment by dsnjunior** [comment]
Nice! Thanks for your help! Let me know if I can help somehow 😁

**Comment by bholmesdev** [comment]
Ah no problem! Just use the library and leave any idas or feedback on our discord. You can find the `#simple-stack` channel here: https://discord.gg/jGwU5xNU
